fix use core::fmt to std::fmt because no_std
rust playground can compile but rustc cannot work with core::fmt.
Will confuse beginner if they try to compile with rustc offline.
```
error[E0433]: failed to resolve: maybe a missing crate `core`?
     |     use core::fmt::Display;
    |         ^^^^ maybe a missing crate `core`?
    |
    = help: consider adding `extern crate core` to use the `core` crate
```